SELECT * FROM [COVI_SMART].[dbo].ORG_ENTERPRISE AS COMPANY

SELECT *  FROM [COVI_SMART].[dbo].ORG_UNIT AS TEAM

SELECT * FROM [COVI_SMART].[dbo].ORG_JOBLEVEL AS JOBLEVEL

SELECT * FROM [COVI_SMART].[dbo].ORG_JOBTITLE AS JOBTITLE