SELECT * FROM [COVI_SMART].[dbo].ORG_ENTERPRISE AS COMPANY

SELECT *  FROM [COVI_SMART].[dbo].ORG_UNIT AS TEAM

SELECT * FROM [COVI_SMART].[dbo].ORG_JOBLEVEL AS JOBLEVEL

SELECT * FROM [COVI_SMART].[dbo].ORG_JOBTITLE AS JOBTITLE


SELECT
    COLUMN_NAME
FROM
    INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE
    OBJECTPROPERTY(OBJECT_ID(CONSTRAINT_NAME), 'ISPRIMARYKEY') = 1
    AND
        TABLE_NAME = OrgPerson

